export enum Tag {
  BINARY_SEARCH = 'binary search',
  BITMASKS = 'bitmasks',
  BRUTE_FORCE = 'brute force',
  COMBINATORICS = 'combinatorics',
  CONSTRUCTIVE_ALGORITHMS = 'constructive algorithms',
  DATA_STRUCTURES = 'data structures',
  DFS_AND_SIMILAR = 'dfs and similar',
  DP = 'dp',
  GAMES = 'games',
  GEOMETRY = 'geometry',
  GRAPH_MATCHINGS = 'graph matchings',
  GRAPHS = 'graphs',
  GREEDY = 'greedy',
  IMPLEMENTATION = 'implementation',
  INTERACTIVE = 'interactive',
  MATH = 'math',
  MATRICES = 'matrices',
  NUMBER_THEORY = 'number theory',
  PROBABILITIES = 'probabilities',
  SORTINGS = 'sortings',
  STRINGS = 'strings',
  TREES = 'trees',
  TWO_POINTERS = 'two pointers',
}
